### ISSUE TITLE
Отображение к конфигам 

### ISSUE THREAD

**Issue by bazilsafronov** [anzix/dotfiles#1]
**Привет**! Было бы круто, если например в папке i3wm, в том же полибаре или пиком, были бы скриншоты рабочего стола, чтобы наглядно было посмотреть как это будет выглядеть.

**Comment by anzix** [comment]
Привет, да, я думал над этим, но так как я сейчас использую окружение Plasma в качестве основного окружения, руки не доходят до i3wm, в том числе и sway (но есть желание снова вернутся на тайлинги). Пожелание ваше учту, оставлю пока открытой

**Comment by anzix** [comment]
Скриншоты добавлены
